apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-sso-secret 
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: grafana-sso-secret 
    creationPolicy: Owner

  data:
    - secretKey: github.org 
      remoteRef: 
        key: grafana_sso_org
    - secretKey: github.clientID 
      remoteRef: 
        key: grafana_sso_client_id
    - secretKey: github.clientSecret 
      remoteRef: 
        key: grafana_sso_client_secret