helmCharts:
- includeCRDs: true
  name: kube-prometheus-stack
  namespace: monitoring 
  releaseName: kube-prometheus-stack 
  repo: https://prometheus-community.github.io/helm-charts
  version: 59.0.0
  valuesFile: values.yaml