apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    - monitoring.cluster.webstra.dev
    secretName: monitoring-tls 
  rules:
  - host: monitoring.cluster.webstra.dev
    http:
      paths:
        - path: /grafana
          pathType: Prefix
          backend:
            service:
              name: kube-prometheus-stack-grafana 
              port:
                number: 80
