grafana:
  envValueFrom:
    GF_AUTH_GITHUB_CLIENT_ID:
      secretKeyRef:
        name: grafana-sso-secret
        key: github.clientID
    GF_AUTH_GITHUB_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-sso-secret
        key: github.clientSecret
    GF_AUTH_GITHUB_CLIENT_ORG:
      secretKeyRef:
        name: grafana-sso-secret
        key: github.org
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls:
    - hosts:
      - monitoring.cluster.webstra.dev
      secretName: monitoring-tls 
    hosts:
      - monitoring.cluster.webstra.dev 
    path: /grafana/
  grafana.ini:
    server:
      domain: monitoring.cluster.webstra.dev
      root_url: https://monitoring.cluster.webstra.dev/grafana 
      serve_from_sub_path: true
    auth:
      disable_login_form: true
    auth.basic:
      enabled: false
    auth.github:
      enabled: true
      client_id: ${GF_AUTH_GITHUB_CLIENT_ID}
      client_secret: ${GF_AUTH_GITHUB_CLIENT_SECRET}
      scopes: "user:email,read:org"
      auth_url: "https://github.com/login/oauth/authorize"
      token_url: "https://github.com/login/oauth/access_token"
      api_url: "https://api.github.com/user"
      allowed_organizations: ${GF_AUTH_GITHUB_CLIENT_ORG}
