grafana:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - monitoring.cluster.webstra.dev
    tls:
      - secretName: "grafana-tls-key"
        hosts: 
        - monitoring.cluster.webstra.dev
    path: /grafana