grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls:
    - hosts:
      - grafana.cluster.webstra.dev
      secretName: grafana-tls 
    hosts:
      - grafana.cluster.webstra.dev 
    pathType: Prefix
    path: /
  grafana.ini:
  server:
    root_url: https://grafana.cluster.webstra.dev/