apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
- includeCRDs: true
  name: ingress-nginx 
  namespace: ingress-nginx
  releaseName: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.10.1
  valuesFile: nginx-ingress-values.yaml

namespace: ingress-nginx
