apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    g, e.s.westra.95@gmail.com, role:admin
  scopes: '[groups, email]'