apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.cluster.webstra.dev
  kustomize.buildOptions: --enable-helm
  helm.repositories: |
    - name: stable
      url: https://charts.helm.sh/stable
  configManagementPlugins: |
    - name: kustomized-helm
      generate:
        command: [sh, -c]
        args: ["kustomize build --enable-helm"]
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID:  $argocd-sso-key:dex.github.clientID
          clientSecret: $argocd-sso-key:dex.github.clientSecret
          redirectURI: https://argocd.cluster.webstra.dev/auth/github/callback