apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: cilium
  namespace: kube-system
  releaseName: cilium
  repo: https://helm.cilium.io/
  valuesInline:
    endpointRoutes:
      enabled: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    ipam: # Match podCIDR for k3s
      operator:
        clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
        replicas: 1 # Single node cluster
  version: 1.15.6

