apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: cilium
  namespace: kube-system
  releaseName: cilium
  repo: https://helm.cilium.io/
  valuesInline:
    kubeProxyReplacement: true
    endpointRoutes:
      enabled: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
  version: 1.15.6

