apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    gitlab:
      auth:
        secretRef:
          accessToken:
            key: token
            name: gitlab-token
            namespace: external-secrets
      projectID: "58206440"