apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret-test
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: test-secret
    namespace: external-secrets 
    creationPolicy: Owner

  data:
    - secretKey: test_secret
      remoteRef: 
        key: test_secret