resources:
  - namespace.yaml
  - crds/cert-manager-crds.yaml
  - cluster-issuer.yaml

helmCharts:
- includeCRDs: true
  name: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  valuesMerge: merge
  version: v1.14.5
