controller:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

dashboard:
  enabled: true
  service:
    type: ClusterIP

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
