apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  source:
    chart: kargo
    repoURL: oci://ghcr.io/akuity/kargo-charts
    targetRevision: 1.0.0
    helm:
      values: |
        api:
          adminAccount:
            passwordHash: '$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm'
            tokenSigningKey: 'iwishtowashmyirishwristwatch'
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
