resources:
  - namespace.yaml
  - cert-manager-crds.yaml

helmCharts:
- includeCRDs: true
  name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  valuesMerge: merge
  version: v1.14.5
