apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: webserver.cluster.webstra.dev 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webserver 
            port:
              number: 80
