controller:
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-name: "k3s-loadbalancer"
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      # Uncomment and set your certificate ID if using HTTPS
      # service.beta.kubernetes.io/do-loadbalancer-certificate-id: "<your-certificate-id>"
      # service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    type: NodePort
    externalTrafficPolicy: Cluster
    ports:
      http: 80
      https: 443
    targetPorts:
      http: 80
      https: 443
    nodePorts:
      http: 30080
      https: 30443
    selector:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller 
  config:
    use-proxy-protocol: "true"
