controller:
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-name: "k3s-loadbalancer"
      # Uncomment and set your certificate ID if using HTTPS
      # service.beta.kubernetes.io/do-loadbalancer-certificate-id: "<your-certificate-id>"
      # service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"