
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30080  # NodePort range is typically 30000-32767
  - name: https
    port: 443
    targetPort: https
    nodePort: 30443  # NodePort range is typically 30000-32767