apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-secret 
  labels:
    argocd.argoproj.io/secret-type: repository 
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: argocd-repo-secret 
    creationPolicy: Owner

  data:
    - secretKey: name 
      secretValue: main-repo
    - secretKey: type 
      secretValue: git
    - secretKey: url 
      remoteRef: 
        key: argocd_repo_url
    - secretKey: sshPrivateKey 
      remoteRef: 
        key: argocd_repo_ssh_private_key