apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "true"
  url: https://argocd.cluster.webstra.dev
  kustomize.buildOptions: --enable-helm
  helm.repositories: |
    - name: stable
      url: https://charts.helm.sh/stable
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
  configManagementPlugins: |
    - name: kustomized-helm
      generate:
        command: [sh, -c]
        args: ["kustomize build --enable-helm"]
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        loadAllGroups: true
        config:
          clientID:  $argocd-sso-secret:dex.github.clientID
          clientSecret: $argocd-sso-secret:dex.github.clientSecret
          orgs:
            - name: $argocd-sso-secret:dex.github.org
    
