apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  policy.default: |
    g, role:default, role:readonly, deny 
    p, role:default, *, *, *, deny
  policy.csv: |
    p, role:developer, applications, get, *, allow
    p, role:developer, applications, sync, *, allow
    p, role:developer, applications, refresh, *, allow
    p, role:developer, projects, get, *, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, clusters, get, *, allow
    p, role:developer, accounts, get, *, allow
    p, role:developer, logs, get, *, allow

    g, webstrasuite:cluster-admins, role:admin
    g, webstrasuite:developer, role:developer
  scopes: '[groups, email]'