apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-secret 
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository 
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: argocd-repo-secret 
    creationPolicy: Owner
  
  # Use a template to populate the repository name name, repository type and argocd label
  template:
    engineVersion: v2
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repository
    data:
      name: main-repo
      type: git
      url: |-
        {{ .url }}
      sshPrivateKey: |- 
        {{ .sshPrivateKey }}

  data:
    - secretKey: url 
      remoteRef: 
        key: argocd_repo_url
        property: url
    - secretKey: sshPrivateKey 
      remoteRef: 
        key: argocd_repo_ssh_private_key
        property: sshPrivateKey