apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-secret 
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository 
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: argocd-repo-secret 
    creationPolicy: Owner

  data:
    - secretKey: name
      remoteRef:
        key: argocd_repo_secret_name
    - secretKey: type
      remoteRef:
        key: argocd_repo_secret_type
    - secretKey: url 
      remoteRef: 
        key: argocd_repo_url
    - secretKey: sshPrivateKey 
      remoteRef: 
        key: argocd_repo_ssh_private_key