apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "true"
  url: https://argocd.cluster.webstra.dev
  kustomize.buildOptions: --enable-helm
  helm.repositories: |
    - name: stable
      url: https://charts.helm.sh/stable
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
  configManagementPlugins: |
    - name: kustomized-helm
      generate:
        command: [sh, -c]
        args: ["kustomize build --enable-helm"]
    - name: helm-kustomize
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: |
          - |
            # Create temp directory for kustomize
            TEMP_DIR=$(mktemp -d)
            trap "rm -rf $TEMP_DIR" EXIT
            
            # Generate helm template directly into kustomization.yaml
            helm template . --values values.yaml > "$TEMP_DIR/kustomization.yaml"
            
            # Run kustomize build
            cd "$TEMP_DIR"
            kubectl kustomize . --enable-helm
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        loadAllGroups: true
        config:
          clientID:  $argocd-sso-secret:dex.github.clientID
          clientSecret: $argocd-sso-secret:dex.github.clientSecret
          orgs:
            - name: $argocd-sso-secret:dex.github.org
    
