apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-secret 
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository 
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: argocd-repo-secret 
    creationPolicy: Owner
  
  # Use a template to populate the name, type and labels
  template:
    templateFrom:
    - configMap:
        name: argocd-repo-secret-cm
        items: 
        - key: argocd-repo-secret-cm.yaml

  data:
    - secretKey: url 
      remoteRef: 
        key: argocd_repo_url
    - secretKey: sshPrivateKey 
      remoteRef: 
        key: argocd_repo_ssh_private_key