apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-repo-secret.yaml
- argocd-sso-secret.yaml
- argocd-ingress.yaml

helmCharts:
- includeCRDs: true
  name: argo-cd
  namespace: argocd
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  valuesMerge: merge
  version: 5.51.6


patches:
- path: ./argocd-cm.yaml
- path: ./argocd-rbac-cm.yaml

namespace: argocd
