apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustom/nginx-ingress/overlays
    repoURL: git@github.com:webstradev/argo-dev-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true