apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps.yaml
  - argo-cd/application.yaml
  - nginx-ingress/application.yaml
  - webserver/application.yaml
  - cert-manager/application.yaml
  - vault/application.yaml

namespace: argocd