apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps.yaml
  - argo-cd/application.yaml
  - cilium/application.yaml
  - cert-manager/application.yaml
  - cluster-secret-store/application.yaml
  - external-secrets/application.yaml
  - kube-prometheus-stack/application.yaml
  - namespaces/application.yaml
  - nginx-ingress/application.yaml
  - webserver/application.yaml
  - argo-rollouts/application.yaml
  - kargo/application.yaml

namespace: argocd
