apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps.yaml
  - applications/argo-cd.yaml
  - applications/nginx-ingress.yaml
  - applications/webserver.yaml
  - applications/cert-manager.yaml

namespace: argocd