apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store 
  namespace: argocd
spec:
  destination:
    namespace: external-secrets 
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/cluster-secret-store
    repoURL: git@github.com:webstradev/argo-dev-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true