apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces 
  namespace: argocd
spec:
  destination:
    namespace: namespaces 
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/namespaces
    repoURL: git@github.com:webstradev/argo-dev-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true